---
# tasks file for mapr-opentsdb

- name: install git
  become: yes
  become_user: root
  yum: name=git state=present
  environment: proxy_env

- name: download forked tcollector
  become: yes
  become_user: root
  git: repo=https://github.com/vicenteg/tcollector.git version=ISSUE-196 dest=/opt/tcollector force=yes
  environment: proxy_env
  
- name: link tcollector start stop script to /etc/init.d
  become: yes
  become_user: root
  file: state=link src=/opt/tcollector/startstop dest=/etc/init.d/tcollector

- name: install tcollector.service on CentOS/RHEL 7
  become: yes
  become_user: root
  copy: src=tcollector.service dest=/etc/systemd/system/tcollector.service owner=root group=root mode=0644
  when: ansible_distribution in ('RedHat', 'CentOS') and ansible_distribution_major_version == "7"

- name: edit start stop script to point to tsd 
  become: yes
  become_user: root
  lineinfile: dest=/opt/tcollector/startstop regexp="^#\s+TSD_HOST" line="TSD_HOST={{groups["opentsdb"][0]}}" backup=true

- name: tell startstop where tcollector is installed
  become: yes
  become_user: root
  lineinfile: dest=/opt/tcollector/startstop line="TCOLLECTOR_PATH=/opt/tcollector" insertafter="^#!" backup=true 

- name: create collectors/etc/mapr_metrics from template
  become: yes
  become_user: root
  template: src=etc.mapr_metrics_conf.py.j2 dest=/opt/tcollector/collectors/etc/mapr_metrics_conf.py backup=true

- name: start tcollector
  become: yes
  become_user: root
  service: name=tcollector state=started
